version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./charts:/app/charts
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
